export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const SET_REMOTE_STREAM = 'SET_REMOTE_STREAM';
export const ADD_TRACK_PC = 'ADD_TRACK_PC';
export const ADD_TRACK_REMOTE_STREAM = 'ADD_TRACK_REMOTE_STREAM';
export const SET_WEBCAM_VIDEO = 'SET_WEBCAM_VIDEO';
export const SET_REMOTE_VIDEO = 'SET_REMOTE_VIDEO';
export const SET_CALL_BUTTON = 'SET_CALL_BUTTON';
export const SET_ANSWER_BUTTON = 'ANSWER_CALL_BUTTON';
export const TOGGLE_WEBCAM = 'TOGGLE_WEBCAM';
export const SET_CALL_INPUT = 'SET_CALL_INPUT';
export const SET_HANGUP_BUTTON = 'SET_HANGUP_BUTTON';
//pc

export const SET_PC = 'SET_PC';

export const SET_MEETING_TYPE = 'SET_MEETING_TYPE';
export const SET_MEETING_LEFT = 'SET_MEETING_LEFT';
